### PR TITLE
CME Enum commands + SMB Exec

### PR DESCRIPTION
**Pull request by Bad-Jubies**

### CODE REVIEW

**Comment by JohnWoodman** [comment]
These are awesome! Would you be able to put all the enumeration commands into one command by just combining the flags? The reason for this is so we don't clutter the site with commands that are nearly identical. The Exec-Share one can be it's own command because its purpose differs from the rest. Thanks!

**Comment by Bad-Jubies** [comment]
> 
> 
> These are awesome! Would you be able to put all the enumeration commands into one command by just combining the flags? The reason for this is so we don't clutter the site with commands that are nearly identical. The Exec-Share one can be it's own command because its purpose differs from the rest. Thanks!

sure thing

**Comment by Bad-Jubies** [comment]
@JohnWoodman should be good now!

**Comment by JohnWoodman** [comment]
Awesome! Merging now. Thanks for contributing!

**Pull request merged**
